# Generated by Django 6.0.3 on 2026-03-15 09:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0002_remove_task_status_task_deadline'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='status',
            field=models.CharField(choices=[('todo', 'TODO'), ('in_progress', 'IN PROGRESS'), ('done', 'DONE')], default='todo', max_length=20),
        ),
    ]
