# Generated by Django 6.0.3 on 2026-04-06 07:28

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0003_task_status'),
        ('workspaces', '0003_workspace_is_deleted_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='is_deleted',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='task',
            name='status',
            field=models.CharField(choices=[('todo', 'TODO'), ('in_progress', 'IN PROGRESS'), ('review', 'REVIEW'), ('done', 'DONE')], default='todo', max_length=20),
        ),
        migrations.AddIndex(
            model_name='task',
            index=models.Index(fields=['workspace', 'status'], name='tasks_task_workspa_58e2a8_idx'),
        ),
        migrations.AddIndex(
            model_name='task',
            index=models.Index(fields=['assign_to', 'status'], name='tasks_task_assign__5fef6f_idx'),
        ),
    ]
